### PR TITLE
Adding the TextSearch call

### PR DESCRIPTION
**Pull request by Dynom**

### CODE REVIEW

**Comment by maxhawkins** [comment]
Thank you for the contribution!

I'd love to merge this. Could you add some tests and fix up the linter errors I posted as comments? Other than that this looks great.

**Comment by Dynom** [comment]
I've fixed all linter suggestions and added a couple of tests for my changes. However to fix all linter issues I suggest a different PR since that is outside the scope of this feature.

**Comment by maxhawkins** [comment]
Thanks for the updates. I posted a few nits—mostly about the doc strings.

**Comment by Dynom** [comment]
Done.

**Comment by maxhawkins** [comment]
LGTM. Thanks a lot Mark!

**Comment by Dynom** [comment]
Hmm, actually. I introduced a bug in the last cleanup. I removed a check from the validator that was essential to pagination requests.

**Comment by maxhawkins** [comment]
Oops. I should have reviewed it more carefully.

I rolled back. Just open a new PR with the fix.

**Comment by Dynom** [comment]
Hm. I'm not sure what's going on actually, I've corrected the thing I thought caused the bug, but thats not it. For some reason all multi-page requests fail

**Comment by Dynom** [comment]
I thought it was a problem in the validation function, since I removed the following:

``` go
func (t *TextSearchCall) validate() error {
    if t.PageToken != "" {
        return nil
    }
```

But since I had pagination errors I re-examined the code and noticed that I overlooked an implementation detail, that validation works differently on subsequent requests (since only the `pageToken` is passed along). I corrected that (for which I will send a PR momentarily), but I still have the problem.

This is my implementation:

``` go
    call := p.service.TextSearch(query)

    var results []places.PlaceDetails

    for {
        resp, err := call.Do()
        if places.IsZeroResults(err) {
            log.Printf("Had 0 results, skipping this run '%s'\n%s.", err, resp)
            break
        }

        if places.IsInvalidRequest(err) {
            log.Printf("The request was invalid! '%s'.\n%s", err, resp)
            time.Sleep(100 * time.Millisecond) // Rate limit
            break
        }

        if err != nil {
            panic(err)
        }

        results = append(results, resp.Results...)
        if resp.NextPageToken != "" {
            log.Println("Got multiple results, fetching next page")
            call.PageToken = resp.NextPageToken
        } else {
            break
        }
    }

    if len(results) > 0 {
            ...
```

The output I get is:

```
The request was invalid! 'INVALID_REQUEST'.
%!s(*places.SearchResponse=<nil>)
```

Do you have any suggestions @maxhawkins ?

**Comment by Dynom** [comment]
@maxhawkins I'm not sure it's my implementation or a bug in the library in general...

**Comment by maxhawkins** [comment]
I tried looking at the generated search URL:

``` go
searchURL := baseURL + "/textsearch/json?" + t.query()
fmt.Println(searchURL) // <----
resp, err := t.service.client.Get(searchURL)
```

This prints...

```
https://maps.googleapis.com/maps/api/place/textsearch/json?key=<key>&location=0.000000%2C0.000000&query=cafe
```

It seems you're not checking if the location isn't provided. Add this and it should work:

``` go
if t.lat != 0 && t.lng != 0 {
    query.Add("location", fmt.Sprintf("%f,%f", t.lat, t.lng))
}
```

**Comment by Dynom** [comment]
Hi @maxhawkins 

yeah, I found that one also. I fixed it like so, which is basically the same:

``` go
if t.lat > 0 && t.lng > 0 {
        query.Add("location", fmt.Sprintf("%f,%f", t.lat, t.lng))
    }

```

However, that shouldn't matter on the pagination requests, should it? The problem lies within the logic handling the `NextPageToken` flow.

**Comment by Dynom** [comment]
I've updated the `Do()` function with the following code:

``` go
// ...
    searchURL := baseURL + "/textsearch/json?" + t.query()
    req, _ := http.NewRequest("GET", searchURL, nil)
    resp, err := t.service.client.Do(req)

    reqBody, _ := httputil.DumpRequest(req, true)
    respBody, _ := httputil.DumpResponse(resp, true)
    fmt.Println("---[ Request ]----------------------")
    fmt.Println(string(reqBody))
    fmt.Println("---[ Response ]---------------------")
    fmt.Println(string(respBody))

    // resp, err := t.service.client.Get(searchURL)
    if err != nil {
        return nil, err
    }

// ...
```

I noticed the following subsequent request / responses:

Request

```
GET /maps/api/place/textsearch/json?key=APIKEY&pagetoken=SOME_EXCESSIVELY_LONG_TOKEN HTTP/1.1
Host: maps.googleapis.com
```

I've matched the excessively long token with the one from the previous response, and they match.

Response

```
TTP/1.1 200 OK
Transfer-Encoding: chunked
Alt-Svc: quic=":443"; p="1"; ma=604800
Alternate-Protocol: 443:quic,p=1
Cache-Control: public, max-age=300
Content-Type: application/json; charset=UTF-8
Date: Tue, 24 Nov 2015 19:07:42 GMT
Expires: Tue, 24 Nov 2015 19:12:42 GMT
Server: mafe
Vary: Accept-Language
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

54
{
   "html_attributions" : [],
   "results" : [],
   "status" : "INVALID_REQUEST"
}

0
```

I'm unsure where the garbage comes from (the number's `54` / `0`), but I'm fairly certain that those are not part of the problem.

When I paste the generated URL in my browser, I get a valid response and I get the next 20 (or so) results from my initial query.

**Comment by maxhawkins** [comment]
It's working fine for me. Here's the code I used:

``` go
package main

import (
    "flag"
    "fmt"
    "net/http"
    "time"

    "github.com/maxhawkins/google-places-api/places"
)

func main() {
    key := flag.String("key", "", "google places api key")
    flag.Parse()

    service := places.NewService(http.DefaultClient, *key)

    call := service.TextSearch("cafe")

    resp, err := call.Do()
    if places.IsZeroResults(err) {
        fmt.Println("no results")
        return
    }
    if err != nil {
        panic(err)
    }

    results := resp.Results
    token := resp.NextPageToken

    for token != "" {
        time.Sleep(2 * time.Second) // Rate limit

        call.PageToken = token
        resp, err := call.Do()
        if err != nil {
            panic(err)
        }

        token = resp.NextPageToken
        results = append(results, resp.Results...)
    }

    for _, result := range results {
        fmt.Println(result.Name)
    }
}
```

**Comment by Dynom** [comment]
Thanks @maxhawkins. I've reviewed it a couple of times, the only _real_ difference is the timeout.. I'll try that next.

**Comment by Dynom** [comment]
Holy crap, that was it.. raising the timeout solved it.

Google, you suck at building web services.

**Comment by maxhawkins** [comment]
Haha. Yeah this API is pretty jank.

Can you re-open the pull request with the lat/lng change?

**Comment by Dynom** [comment]
Sure. Thanks for the help @maxhawkins !

**Pull request merged**
