### PR TITLE
Adding text search call

### PR DESCRIPTION
**Pull request by Dynom**

### CODE REVIEW

**Comment by maxhawkins** [comment]
I think this PR is missing some commits. Could you rebase off of my master?

**Comment by Dynom** [comment]
yeah, I was trying to figure out where it went wrong. I thought you reverted the branch, but you didn't?

**Comment by Dynom** [comment]
Not sure why it won't merge cleanly, it's up to date with your master branch.

**Comment by Dynom** [comment]
Did you push your master? I've brought mine up-to-date with yours and the merge applies cleanly.

**Comment by maxhawkins** [comment]
Hm, that's strange. Try this:

```
git reset --hard f8ce790   # undo the merge
git remote add max https://github.com/maxhawkins/google-places-api.git   # add my repo as a remote
git pull max   # grab it
git rebase max/master   # rebase your changes on top of my master
```

**Comment by Dynom** [comment]
yeah I've done something similar, but I didn't do a rebase, since it seems you didn't merge the revert back.

**Comment by maxhawkins** [comment]
Maybe you have an outdated version? The merge is here: https://github.com/maxhawkins/google-places-api/commit/e244256dec21afb1145b55e58d80fcb64c611857

**Comment by Dynom** [comment]
There we go.

**Comment by Dynom** [comment]
No this is not correct, a semantical merge conflict, sigh. I'll fix it.

**Comment by Dynom** [comment]
```
go test -v ./...
=== RUN   TestDetailsCallDo
--- PASS: TestDetailsCallDo (0.00s)
=== RUN   TestNearbyCallValidate
--- PASS: TestNearbyCallValidate (0.00s)
=== RUN   TestTextSearchValidate
--- PASS: TestTextSearchValidate (0.00s)
=== RUN   TestNewService
--- PASS: TestNewService (0.00s)
=== RUN   TestSetURL
--- PASS: TestSetURL (0.00s)
PASS
ok      github.com/Dynom/google-places-api/places   0.014s
```

There we go.

**Comment by maxhawkins** [comment]
Thanks!

**Pull request merged**
